### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by aidabeorn** [danzasphere/ets2jobssync#1]
Please provide a license for the project.

**Comment by digoot** [comment]
Is enough with a CC license?

**Comment by aidabeorn** [comment]
To be approved on the forums it has to be a [FSF approved license](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#Approvals), from a purely technical standpoint CC is meant for creative works (hence the name _Creative_ Commons) with the exception of zero.

**Comment by danzasphere** [comment]
I have added the GNU license now

**Comment by aidabeorn** [comment]
Make sure to add a LICENSE file with the license in the root of the repository to make it clear what exact license you're releasing it under ;)

**Comment by danzasphere** [comment]
Its added to the root ;)
